apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{ include "helpers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if semverCompare ">=1.20" .Capabilities.KubeVersion.Version }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
  {{- end }}
  ports:
    - port: 7070
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "helpers.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
