apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: golang-api
build:
  local:
    useBuildkit: true
  artifacts:
    - image: golang-api
      context: ../../src/golang/
      docker:
        dockerfile: ../../ops/dockerfile/golang-api.Dockerfile
        target: builder
      sync:
        infer:
          - 'src/golang/**'
deploy:
  helm:
    releases:
      - name: golang-api
        namespace: remote-debug
        chartPath: ../Helm/server-api
        wait: true
        setValues:
          image: golang-api
        setValueTemplates:
          deploy.image.repository: "{{.IMAGE_REPO}}:{{.IMAGE_TAG}}"
portForward:
  - resourceType: service
    resourceName: golang-api-server-api
    namespace: remote-debug
    port: 7070
    # localPort: 7070
