apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: python-api
build:
  local:
    useBuildkit: true
  artifacts:
    - image: python-api
      context: ../../src/python/
      docker:
        dockerfile: ../../ops/dockerfile/python-api.Dockerfile
      sync:
        infer:
          - 'src/python/**'
deploy:
  helm:
    releases:
      - name: python-api
        namespace: remote-debug
        chartPath: ../Helm/server-api
        wait: true
        setValues:
          image: python-api
        setValueTemplates:
          deploy.image.repository: "{{.IMAGE_REPO}}:{{.IMAGE_TAG}}"
portForward:
  - resourceType: service
    resourceName: python-api-server-api
    namespace: remote-debug
    port: 7070
    # localPort: 7070
